# Generated by Django 3.0.4 on 2020-04-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200331_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='manager',
        ),
    ]
