# Generated by Django 3.0.4 on 2020-04-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumetemplates',
            name='script',
        ),
        migrations.AddField(
            model_name='resumetemplates',
            name='jsFile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
